### PR TITLE
Updated valid move, edited is_obstructed? and sorted update_game bug

### PR DESCRIPTION
**Pull request by CharlieTyler**
https://github.com/apolishch/dreamteam/issues/84 - Fixed by including 'update' in :authenticate_user

https://github.com/apolishch/dreamteam/issues/55 - Sorted and changed is_obstructed? to work correctly

### CODE REVIEW

**Comment by jayj10080** [comment]
I also debugged is_obstructed?  There will be a merge conflict between our 2 versions of is_obstructed?

**Comment by jayj10080** [comment]
I recommend going with my version of is_obstructed? seeing that I got some help from a 10+ years experience Github employee.

**Comment by CharlieTyler** [comment]
@jayj10080 yeah can do, I don't quite understand your version of is_obstructed? and the simple change I added of changing it to a negative worked for my tests so that is why I have it in this pull request.

**Comment by CharlieTyler** [comment]
Also my failing tests are because these tests need updating. They are due to changing the is_obstructed? method and how a game is accessed through the show method. Old tests need updating basically..

**Comment by CharlieTyler** [comment]
Changed to new branch as messed up loads 😭

**Pull request closed without merging**
